services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    labels:
      - deunhealth.restart.on.unhealthy=true
    volumes:
      - grafana:/var/lib/grafana
    ports:
      - 3000:3000
    healthcheck:
      test: curl --fail http://localhost:3000/api/health || exit 1
      interval: 60s
      retries: 3
      start_period: 20s
      timeout: 10s
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    labels:
      - deunhealth.restart.on.unhealthy=true
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    extra_hosts:
      - "${HOSTNAME}:host-gateway"
    volumes:
      - prom:/etc/prometheus
      - prom_data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    healthcheck:
      test: curl --fail http://localhost:9090/-/healthy || exit 1
      interval: 60s
      retries: 3
      start_period: 20s
      timeout: 10s
    restart: unless-stopped

  deunhealth:
    image: qmcgaw/deunhealth
    container_name: deunhealth
    network_mode: "none"
    environment:
      - LOG_LEVEL=info
      - HEALTH_SERVER_ADDRESS=127.0.0.1:9999
      - TZ=${TZ}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  portainer:
    image: portainer/portainer-ee:lts
    container_name: portainer
    labels:
      - deunhealth.restart.on.unhealthy=true
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    ports:
      - 9000:9000
    healthcheck:
      test: curl --fail http://localhost:9000/api/system/status || exit 1
      interval: 60s
      retries: 3
      start_period: 20s
      timeout: 10s
    restart: always

volumes:
  grafana:
  prom:
  prom_data:
  portainer:

networks:
  default:
    external: true
    name: tailscale-net
