services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - plex:/config
      - /data:/data
    devices:
      - /dev/dri:/dev/dri
    ports:
      - 32400:32400
    restart: unless-stopped


volumes:
  plex:

networks:
  default:
    external: true
    name: tailscale-net